### ISSUE TITLE
run xelatex in nonstopmode

### ISSUE THREAD

**Issue by friendly** [rstudio/tinytex#452]
This is a follow-up here to one point I raised in https://github.com/quarto-dev/quarto-cli/discussions/11087,
namely, how to have TinyTeX not stop the LaTeX compile on the first error.

From https://quarto.org/docs/output-formats/pdf-engine.html I tried seting the `pdf-engine-opt` as follows in my `_config.yml`,
but this has no effect -- 

```
  pdf-engine-opt: 
    interaction: nonstopmode
  pdf:
    documentclass: krantz
    classoption: [10pt, krantz2]
    include-in-header: latex/preamble.tex
    include-before-body: latex/before-body.tex
    include-after-body: latex/after-body.tex
    keep-tex: true
    latex-tinytex: true
    geometry:
      - top=20mm
      - left=25mm
    code-block-bg: 'E8FFFF'  #'#f1f1f1'
```

Compilation still stops at the first latex error:

```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Package amsmath Error: Erroneous nesting of equation structures;
(amsmath)                trying to recover with `aligned'.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9659 \end{align*}
```
